### ISSUE TITLE
Parameter documentation?

### ISSUE THREAD

**Issue by tbarchyn** [IM3S/LDAR_Sim#12]
@KeeganShaw-GIS Soroush @tarcadius - your thoughts on the below?

A method to update documentation as we go might be helpful, and make that documentation part of the code base so changes come in with both code changes, and the changes to documentation. You all have done fantastic work with first round, but having something part of the code base could be an enhancement?

Generally, there are probably 3 sets of documentation:
1) method level - documentation for parameters, what the method does, etc. - the way to do this is probably sphinx: https://www.sphinx-doc.org/en/master/   - parameters, defaults, units, etc. for each method in the docstring at the start of the method. This is probably already a PEP8 thing already, I'm not certain. This documentation is aimed at people taking the model apart and putting it back together again.

2) parameter level - documentation for model parameters in the input parameter files. This defines what columns need to be in the input spreadsheets, and what every single parameter does. This is aimed at people who want to run the model but aren't taking it apart. I think you all have already made this - but should it be part of the code, so it can be updated? Possibly markdown or something that can be auto-rendered to a pdf?

3) web-app level - documentation for web app people - this is kind of a separate deal and probably will be part of web app code.

Thoughts on this? I'm suggesting possibly doing this way so documentation is kept current and part of pull requests instead of being a big task that someone needs to do later.

**Comment by KeeganShaw-GIS** [comment]
I will add this to the meeting agenda for this week. I like the idea of sphinx.

**Comment by tarcadius** [comment]
Is this related to what @c-vollrath is investigating with GitWiki? I may request to lean on someone else to lead this issue and let them teach me as they go, but sounds like a good idea to have everything well documented and cross referenced internally. Will save much future pain.

**Comment by tbarchyn** [comment]
Closing this one for now - I think we are mostly there with the new markdown. Docstrings still need some work here and there, but we can clean this up with time.
