### ISSUE TITLE
User prompt for pregen leaks vs. batch running

### ISSUE THREAD

**Issue by tbarchyn** [IM3S/LDAR_Sim#138]
Is there benefit introducing a parameter to turn this user interface prompt off, or opposite, turning it on?

Just nervous about this as celery tasks will timeout and fail in web app if this ever pops up in production. (I realize I probably approved this in a PR a few months back!, sorry for flip flop).

https://github.com/IM3S/LDAR_Sim/blob/71ddd67077bfa54c744c9dd1fa1b04e877152d5f/LDAR_Sim/src/ldar_sim_main.py#L82

**Comment by KeeganShaw-GIS** [comment]
This has been fixed , if files have changed it will overwrite,
