### ISSUE TITLE
No P_none in economics raises, then crashes - softly return instead?

### ISSUE THREAD

**Issue by tbarchyn** [IM3S/LDAR_Sim#144]
This `raise` crashes the program if `P_none` is not supplied - would it be better to softly return here (maybe with a note) to allow the program to run without crashing?

https://github.com/IM3S/LDAR_Sim/blob/71ddd67077bfa54c744c9dd1fa1b04e877152d5f/LDAR_Sim/src/economics/cost_mitigation.py#L61

I don't understand why this raises an exception - apologies if I'm missing context.

**Comment by c-vollrath** [comment]
Resolved with P_none issue.
