### ISSUE TITLE
Fixed Sensor Module - Add Equipment scale switch

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [IM3S/LDAR_Sim#15]

**Comment by KeeganShaw-GIS** [comment]
Sweet Idea. I like it @tarcadius

**Comment by KeeganShaw-GIS** [comment]
``asdfjklsdhasdfsda

**Comment by tarcadius** [comment]
Wouldn't we want a generic switch that could be used for any module? For example by specifying the scale of measurement? Or am I not understanding this one ... is there something specific to fixed sensors?

**Comment by KeeganShaw-GIS** [comment]
Uncluded in some previous version
