### ISSUE TITLE
P_none Error

### ISSUE THREAD

**Issue by soroushojagh** [IM3S/LDAR_Sim#150]
Hi all, 

I am getting this error when I remove the P_none.yaml file from the simulations folder:

![image](https://user-images.githubusercontent.com/7353483/138830834-1f7f8b36-8fd6-4a8f-86e2-56c47df0291b.png)

**Do we need to keep P_none always in the simulations folder?** 

**Please note** that I have already changed the _G_.yaml_ file as follow: 

`reference_program: P_air
baseline_program: P_OGI`

**Comment by c-vollrath** [comment]
Resolved! Forgot to close this a few weeks ago.
