### ISSUE TITLE
Weather envelopes

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#21]
We should have consistent weather envelopes for ALL technologies, even if they don't apply. These should be lists that bound the envelope. I know it doesn't make sense for there to be a minimum precipitation, but we should probably be consistent?

To make it work, we'll have to use >= and <=. Let me know if this is just a bad idea. I kind of like it because it forces every technology to make a decision on every variable. @tbarchyn @KeeganShaw-GIS @AkaMrmuffin  Please comment.

temp = [-40, 40]
wind_speed = [0, 30]
precip = [0, 0]
cloud_fraction = [0, 50]
RH% = [2, 98]
etc. etc.

**Comment by tbarchyn** [comment]
Sure, there is the odd winter storm in AB where nobody can really do anything involving roads, never mind planes, so it seems reasonable to set the thresholds by default to make sure nobody gets any work done those days.

**Comment by AkaMrmuffin** [comment]
Agree, this also can be used as a baseline of scheduling to guide LDAR.

**Comment by tarcadius** [comment]
Keegan or Mo do you want to implement this?

**Comment by tarcadius** [comment]
@KeeganShaw-GIS  or @AkaMrmuffin  can one of you implement this?

**Comment by AkaMrmuffin** [comment]
I can implement this. I will add another deployment days filter inside the weather_lookup.py. I also think only temperature, wind speed and precip should be considered in the envelopes.
