### ISSUE TITLE
Improve metadata outputs

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#34]
The purpose of the metadata is to remind you, when you come back to a folder of outputs, what you did!

It might be better to just push all parameters and programs through to the other side, rather than worrying about formating a metadata file.

So, 1. get rid of metadata, and 2. push through all inputs so that inputs are stored in a folder in the outputs?

Obviously don't push through netcdf files...

@tbarchyn @AkaMrmuffin @KeeganShaw-GIS  thoughts?

**Comment by tbarchyn** [comment]
Yes, I was going to ask about the metadata and whether it was in use or could be depreciated. I will look at writing the parameters to the output folder so it is there, ready to re-run if you wish, and of course, a record of the parameters that made the graphs, data, etc.

**Comment by tarcadius** [comment]
@tbarchyn awesome, let's depreciate metadata then. That output file is dumb and I take full responsibility!

**Comment by tbarchyn** [comment]
OK, seems reasonable.

**Comment by KeeganShaw-GIS** [comment]
This has been closed via yaml.
