### ISSUE TITLE
Operator

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#36]
Finish working on operator...

1. Have kill date for each leak
2. Have operator visitation schedule - operator can draw from AVO, soap, OGI, or "passive" - each with different detection probabilities. For this to work properly, a certain % of leaks might have to be "undetectable" by operators.

thoughts? 

@KeeganShaw-GIS @tbarchyn @AkaMrmuffin @c-vollrath

**Comment by tbarchyn** [comment]
I'm in favour of splitting the operator into two:
* conventional LDAR style operator, with some bad MDL that finds leaks, etc.
* refit operator that periodically renews certain equipment, killing all leaks on that equipment

The model will probably not be in any equilibrium over normal time scales - eventually the large leaks will equilibriate against the MDL of the operator, and eventually the small leaks will equilibriate based on the refit frequency - but both of these will take a really long time.

**Comment by tarcadius** [comment]
Sounds good. Yup, I'll test this out. Probably need an "ambition" or "apathy" parameter too... to deal with "detect and ignore"
