### ISSUE TITLE
Improve economics

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#39]
For example, what is the cost of each leak?
New input - price of natural gas
New input - carbon tax

Improve economics! More informative outputs!

(maybe this is too general)

@tbarchyn @KeeganShaw-GIS @c-vollrath 

Assigning this one to @c-vollrath

**Comment by c-vollrath** [comment]
These are great ideas! One of the most informative outputs in terms of economics, I think, could be the cost of an LDAR program less the cost of "producer value." You mentioned a couple like the cost of natural gas - this is money in the bank for producers if they reduce leaks and keep gas in their infrastructure and pipes! Imagine showing a producer that they're going to generate more revenue by doing LDAR than what they have to pay service providers. The carbon tax is a solid one too, and costs could be simulated for future carbon tax price increases - an even better one might be applying the social cost of methane which is ~$27mcf. Implementing an LDAR program will be cheaper than paying a tax at this rate for almost all producers. In general, I think demonstrating how an LDAR program can help producers make more money or add value to their business under different scenarios is an important consideration, and it's something that could help influence broader adoption of LDAR beyond what is required by regulators.

**Comment by tarcadius** [comment]
I agree wholeheartedly with all of this. Excited to run with this topic - this is wide open and completely new! Happy to work with you on this one Coleman to implement your ideas, but I never finished reading Markets and the Environment so I'll leave the executive decisions to you...

**Comment by c-vollrath** [comment]
Love it @tarcadius! If I'm being honest, I still need to finish reading it too...

**Comment by KeeganShaw-GIS** [comment]
Coleman has fixed this stuff
