### ISSUE TITLE
Build in home bases

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#40]
Roads and airports... These need to be optional. We need options around this stuff to keep it simple or crank up the complexity.

This depends on Mo's scheduling plans.

Thoughts

@AkaMrmuffin @tbarchyn @KeeganShaw-GIS

**Comment by AkaMrmuffin** [comment]
I just received spatial data of all airports and cities&towns in Alberta, which can be used as home bases of ground-based LDAR and aircraft-based LDAR. 

For airports, I think we should justify which are available for LDAR aircraft.

**Comment by tarcadius** [comment]
Awesome, that's exciting!

@AkaMrmuffin are you presenting on scheduling this week?? @KeeganShaw-GIS
