### ISSUE TITLE
follow up dependence

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#42]
@tbarchyn @KeeganShaw-GIS @AkaMrmuffin @c-vollrath 

Follow up is unclear how thresholds and proportions interact.

Can either be independent or dependent.

For example, consider FU_thresh is 5 g/s and proportion is 50%

Either you follow up at top 50% of leaks AND everything above 5 g/s (so if there are still 5 g/s leak remaining after the 50% is selected, those ALSO get follow up.

The other way to read it is that all leaks > 5g/s go into a bucket and then 50% of those get follow up.

I think I have a solution:

In program parameter input file, each screening technology gets these two:
          'follow_up_thresh': [True, "independent", 0.27, "absolute"],
          'follow_up_prop': 0.25, # same as before
- First argument is True/False of whether follow-up threshold gets used
- Second argument is "independent" or "compounding" (see below)
- Independent means (either/or) and compounding means that it has to be both
- Third argument is the threshold in g/s
- Fourth argument is used during __init__ (same as before) in case you want to general a threshold based on a percentage of the distribution.

The code for this is (where measured rates are all detection events + quantification error):
        
```
n_sites_to_flag = len(self.candidate_flags) * self.config['follow_up_prop']
n_sites_to_flag = int(math.ceil(n_sites_to_flag))

sites_to_flag = []
measured_rates = []

for i in self.candidate_flags:
    measured_rates.append(i['measured_rate'])
measured_rates.sort(reverse=True)
target_rates = measured_rates[:n_sites_to_flag]

for i in self.candidate_flags:
    if self.config['follow_up_thresh'][0] == False:
        if i['measured_rate'] in target_rates:
            sites_to_flag.append(i)

    elif self.config['follow_up_thresh'][0] == True:
        if self.config['follow_up_thresh'][1] == "independent":
            if i['measured_rate'] in target_rates:
                sites_to_flag.append(i)
            if i['measured_rate'] > self.config['follow_up_thresh'][2]:
                sites_to_flag.append(i) if i not in sites_to_flag else sites_to_flag
        elif self.config['follow_up_thresh'][1] == "compounding":
            if i['measured_rate'] in target_rates:
                if i['measured_rate'] > self.config['follow_up_thresh'][2]:
                    sites_to_flag.append(i)
```

**Comment by tarcadius** [comment]
@tbarchyn @KeeganShaw-GIS @AkaMrmuffin @c-vollrath 

Realizing that the code above doesn't cut it. For "compounding" things could go two different ways:
1. Either you take 50% of all detections and then _of those_ take any that are > 5g/s (in this example)
2. OR you take all leaks > 5g/s and _of those_ take 50%

These are not the same. Currently the code above does option 1 but not option 2. Do we need another parameter to specify this?
@tbarchyn @KeeganShaw-GIS

**Comment by tbarchyn** [comment]
This is tricky - my 2 cents is to make all of the above and various other follow-up schemes options. Then each 'scheme' can be explained in the documents in great detail. There are others too - you could compare against expected emissions, build different 'schemes' for different sites, etc.

This gets really complicated really really fast - but that is fantastic - any logic based follow up scheme should be possible to submit for regulatory approval and there is kind of millions of dollars in optimization that can be unlocked here if it is clear, bulletproof, and everyone can understand it.

I'm in favour of building this whole follow up decision tree as a separate thing that is very well documented as a method of unlocking these more complex schemes for use in real life.

**Comment by tarcadius** [comment]
@tbarchyn Great, I'm in agreement. I might table this until I resolve some easier issues but definitely want to tackle this as part of the method modules and optimization milestone.
