### ISSUE TITLE
LPR made intuitive

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#46]
Should we make LPR more intuitive?

Instead of 0.0065 leaks per site per day, could be 2.3725 leaks per site per year (calculated daily)

Functionally exactly the same.... just more intuitive.

Thoughts? @KeeganShaw-GIS @tbarchyn @AkaMrmuffin @c-vollrath

**Comment by tbarchyn** [comment]
Maybe ... the 0.0065 number has been used elsewhere and we've become a bit familiar with the units and range of numbers ... that would be the counter argument I suppose.

**Comment by tarcadius** [comment]
To be honest the 0.0065 comes from elsewhere but in a different form (I used that number). FEAST has moved to annual numbers of leaks expected to arise. I think it would present a lower barrier of entry for those learning about the model. Fairly superficial though I'm not tied to this.

@c-vollrath @soroushojagh as newer to LDAR-Sim, would love to hear your thoughts on this.

**Comment by c-vollrath** [comment]
@tarcadius @tbarchyn I think LPR represented either way is totally fine! I haven't had any problems interpreting the units of the LPR from day one. It could be left as is, for now, and we can circle back to it later. If the same default and units are being used elsewhere I think we should keep it the same.

**Comment by tarcadius** [comment]
Let's just keep it the way it is. If this is a barrier to entry/learning then we have bigger problems!
