### ISSUE TITLE
Time between sites

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#50]
Time between sites right now is drawn from a bad distribution for road-based systems and a single value for aircraft.

For exploring the impact of this number, the single value can be quite useful and can just approximate site density.

Also, I imaging there is scheduling that will impact this.

I think in the future we need to have a t_bw_sites variable that is "estimated" (based on geography) or "specified" (you just say what it is, either with a value or a distribution).

@tbarchyn @AkaMrmuffin @KeeganShaw-GIS @c-vollrath

**Comment by tbarchyn** [comment]
Fixed fudge factor that is multiplied by euclidian distance as option 1? (this is the ratio between kms to next site and time it takes to drive there, could mine this easy from google maps)

Spatially variable fudge factor multiplied by euclidian distance as more advanced option 2? (ensure this fudge factor is big in the mountains, and small in the plains with good range/township roads).

Proper network analysis module as some future option 3?

**Comment by tarcadius** [comment]
Sound good. Yup, and "single user input value" as option zero (i.e., allow user to assume 5 minutes between all sites constant) - this allows to explore inversely what conditions are required to be profitable/useful.

**Comment by tarcadius** [comment]
@KeeganShaw-GIS  @AkaMrmuffin 

Is this closed/addressed with scheduling?

**Comment by AkaMrmuffin** [comment]
This is addressed with scheduling.
