### ISSUE TITLE
Gettin' Wiki With It

### ISSUE THREAD

**Issue by c-vollrath** [IM3S/LDAR_Sim#51]
Hi all, 
I've been exploring the Git Wiki in more detail - it seems like the best choice to move forward with hosting some sort of more formal documentation on GitHub like the input parameters (compared to just a README). When the Wiki is eventually completed for the public LDAR-Sim repository, users/people can make changes and edits to it, but we'll be able to see who was behind the commits. Is there any concern over this? I think it can also function as a forum where people can ask questions, discuss, and contribute to LDAR-Sim.

Should I do a "pilot" in the private IM3S repository? If yes I'll draft out a skeleton tomorrow and add some examples. Is there anything else that we might want to include on the Wiki page other than the inputs documentation?

@tarcadius @KeeganShaw-GIS @tbarchyn @soroushojagh @AkaMrmuffin 

Will self-assign this one!

**Comment by soroushojagh** [comment]
That seems awesome, thanks. Please keep in mind that it would be better to have different subpages in the wikipage. So, we can keep our documentation updated. Thanks @c-vollrath

**Comment by tarcadius** [comment]
I don't know anything about this but I LOVE the idea of having input param documentation live and updatable and synced with Github!!! Especially if we do versions it will be so much easier to track how parameters and functionality change over time. I say run with it @c-vollrath !

**Comment by tbarchyn** [comment]
@tarcadius  - should this be closed with a migrate to reStructured Text or markdown documentation?  Maybe open new issue for wiki topics or just start 'getting wiki with it' ... and see where the wiki takes us.

**Comment by tarcadius** [comment]
You got it.
