### ISSUE TITLE
Pulling programs' parameters

### ISSUE THREAD

**Issue by soroushojagh** [IM3S/LDAR_Sim#53]
In this task, **program files** (started by "P_" in the input folder) need to be automatically read. In more detail, I am going to:
1. search in the input directory of the project. Find all .txt files started by "P_";
2. fill the drop-down widget with program files. 
3. Then, if the user selects a program, it should automatically read all parameters and show them on this page.

**Comment by tbarchyn** [comment]
@soroushojagh - I'm going to refactor some of this with #7  - I think we are on the same goals with having this hierarchical list of programs and methods, but I think searching the input folder for files that start with 'P_' should be done more directly.

**Comment by soroushojagh** [comment]
@tbarchyn Thanks Thomas. I think this issue needs to be closed. Because:

1. I designed the structure of the DB in such a way that different parameters related to programs and methods will be defined using a new table acting as a tool to define the parameters.
2. Since the input folder is going to reside on the back-end, sending a request to automatically search txt files starting with "P_" would take some time. So, we decided to keep all parameters in a Postgres DB. 

Please feel free to raise any concerns before closing this issue if you think other alternatives might suit the project better.

**Comment by tbarchyn** [comment]
@soroushojagh  OK, sounds like a plan.
