### ISSUE TITLE
Modifying methods' parameters

### ISSUE THREAD

**Issue by soroushojagh** [IM3S/LDAR_Sim#56]
Users can modify some parameters of the selected method. *User_Story: 2-17*

**Comment by tbarchyn** [comment]
@soroushojagh  - do you have clear guidance on what the most important parameters are for user modification in a version 1?

**Comment by soroushojagh** [comment]
@tbarchyn I think we agreed on a few modifiable parameters for version 1. However, as all parameters will be cloned into the user-generated program and methods, so it would be easy to change the status of parameters and let users modify them in future.
