### ISSUE TITLE
Input Parameter Mapper

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [IM3S/LDAR_Sim#59]
The mapper will be a separate module that maps Inputs in a variety of forms to variables used within LDAR-Sim. purpose of the mapper will be too To expand on PR #7:

1. Ensure that changes to current variables do not need to be propagated throughout LDAR-Sim. 
2. Take in a variety of data types to ensure reverse compatibility, and give flexibility for Web app IO development. Allow changes from To expand on PR #7.
3. Allow Excel table-like inputs
3. Clean up code in LDAR_Sim , and LDAR-Sim_run scripts by moving input mapping to a dedicated function. 

This will involve building a single python module for accepting inputs of a variety of types, and validating, then mapping into variables currently used in LDAR-Sim.

**Comment by KeeganShaw-GIS** [comment]
There are atleast six types of inputs:

1. System Parameters: Processing, file locations, etc
2. Global Parameters :  weather, time, number of simulations, etc
3. Program Parameters: LPR, operator params, repair & verification costs.
4. Method Parameters: number of crews, environmental envelops, MDL etc.
5.  Facility Subtype Parameters:  leak rate distributions, survey frequency, time between sites etc. 
6.  Site Parameters: Survey Frequency, Cost, location, name, etc.

The benefits of doing this are to split up parameters so they are easier to manage (like in PR #7 ) and also to allow more flexibility . We could design the mapper in a way that allows the reverse hierarchy where Global parameters can be overwritten by program parameters, method parameters could be overwritten by site parameters... etc.  For example we could set the survey frequency in any of the modules, depending on what we are testing. If we are comparing two of the same programs with different survey frequencies (the same regardless of site and and subtype) we could use the _RS variable in program parameters.  If we want to follow AER D16 we could set that variable in the Facility Subtype Parameters.

Currently, these all exist but int he following form:

1) System Parameters, Global Parameters, and Program Parameters are in each individual program files (text file)
2) Site Parameters - Single CSV
3) Subtype Parameters - Multiple CSVs

**Comment by KeeganShaw-GIS** [comment]
One more type of input : Equipment Scale

**Comment by tbarchyn** [comment]
I'll put together a boilerplate for this when fixing up #7

**Comment by tarcadius** [comment]
Woah, love how you referenced another issue!

**Comment by tbarchyn** [comment]
Closing this one for now as I think it is in a useful form for v2?
