### ISSUE TITLE
Sample sites with replacement

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#60]
replace "random.sample" with "choices" so that replacement occurs when sampling sites.

This will enable you to sample 500 sites for example even if you only have 5 sites in your study. 

Make sure it works - there's a small bug potentially when I tried it the first time. Not sure if there will be issues with redundant facility names or locations.

**Comment by KeeganShaw-GIS** [comment]
@tarcadius There are definitely issues with redundant names, probably need to change the name and location a facility is used multiple times. Not sure about locations @AkaMrmuffin .

**Comment by tarcadius** [comment]
Maybe this is actually a bad idea. If people want to have a very small number of sites, they can just run more sims.
