### ISSUE TITLE
Gettin' down with Markdown

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#62]
Hi all - we are migrating to markdown for documentation that lives and breathes with every branch, repo, etc.

I've done a sample including guidance/rules in the master branch. Please have a look at let me know what you think or dive in there!

@tbarchyn @KeeganShaw-GIS @soroushojagh @c-vollrath @AkaMrmuffin @tybob-gough

**Comment by tbarchyn** [comment]
Good.

**Comment by tbarchyn** [comment]
This is looking great and super practical - going to close this one?
