### ISSUE TITLE
weather param cleanup

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#63]
@KeeganShaw-GIS 

A couple things:

1. Is UTC_offset really a necessary parameter? Can this be calculated automatically as required? In some cases, simulation may span multiple time zones.
2. Is weather_is_hourly necessary? Is there any drawback to deleting this input and just ALWAYS using hourly weather?

@KeeganShaw-GIS can you lead this? @tbarchyn and @AkaMrmuffin  may want to comment.

**Comment by KeeganShaw-GIS** [comment]
@tarcadius 
1) Yah, UTC_offset is a quick fix. Having a UTC offset is nessery for hourly weather calculations but could definitely be automated by adding a timezone library. Not sure how much work would be involved. Be a fun coding problem for someone like @c-vollrath. 

2) No drawback,  except more testing would be required, and it might break some of the other functions. AWS will also have to be updated. @AkaMrmuffin

**Comment by c-vollrath** [comment]
Woah! A time zone library sounds cool, and useful. I'll take a look at this in a week when I'm back! @KeeganShaw-GIS @tarcadius

**Comment by KeeganShaw-GIS** [comment]
Datetime allows a timezone string ie : https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. An we can convert a a time to UTC or vice versa: https://stackoverflow.com/questions/79797/how-to-convert-local-time-string-to-utc. Ignore DLS would be a good way to go about this.

**Comment by AkaMrmuffin** [comment]
If I am correct, converting to UTC time is to benefit the calculation of daylight (sunrise and sunset). But the ERA5 data that we used usually is a subset of regions where only one timezone is included. From my perspective, I don't see the actual need of adding this functionality. However, it may be useful in the future.
