### ISSUE TITLE
emission rate parameter names

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#64]
I think it would add clarity to move from the following for the sake of clarity. Just slightly better (maybe) parameter names - no functional change

**current inputs and comments for leaks**:
```
'leak_file': 'leak_rates.csv',
'subtype_distributions': [False, 'subtype_distributions.csv'], # If True, will overwrite global Leak Dist
'use_empirical_rates': False, # 'sample', 'fit', or False
'leak_rate_dist': ['lognorm',-2.776, 1.462, "kilogram", "hour"]
```

**proposed inputs and comments for leaks**:
```
'leak_dist_source': 'manual', # 'sample', 'fit', or 'manual'
'leak_dist_empirical': 'leak_rates.csv', # Used if leak_dist_source == 'sample' or 'fit'
'leak_dist_manual': ['lognorm',-2.776, 1.462, "kilogram", "hour"] # Used if leak_dist_source == 'manual'
'leak_dist_subtypes': [False, 'subtype_distributions.csv'], # If True, overwrites 'leak_dist_source'
```

@KeeganShaw-GIS  if you agree can you implement and close?

**Comment by KeeganShaw-GIS** [comment]
@tbarchyn @tarcadius 
leak_dist_manual, maybe _curve_ instead of _manual_?  Also what about grouping?

`leak_dist: {
    'source': 'curve',   # 'sample', 'fit', or 'manual'
    'empirical_file': None,  # 'leak_rates.csv'
    'default_curve': ['lognorm',-2.776, 1.462],  
    'subtype_curve_file': None,    # 'subtype_distributions.csv'
    'units': 'kilogram', 
    'increment': 'hour'}`
