### ISSUE TITLE
Remove time_offsite as its replaced with bw_sites

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [IM3S/LDAR_Sim#76]
Rather than having time_offsite and time_bw_sites can we just use one? This is a relic of a mistake from man moons ago... or was this something @tbarchyn  was going to do separately (trying to interpret resolved comment above)

_Originally posted by @tarcadius in https://github.com/IM3S/LDAR_Sim/pull/67#discussion_r663592920_

**Comment by tbarchyn** [comment]
I don't understand these parameters and how they are used?

**Comment by KeeganShaw-GIS** [comment]
@tbarchyn right now t_bw_sites can either be a integer or a string, where the string references a csv file name and is set for each method. It indicates the travel time between sites regardless of travel method. Using string or integer is probably not how we want to proceed, maybe it could be a dict that has a list of default values, and an optional filename? 

`t_bw_sites : {default = [10, 20, 30], file = None} or t_bw_sites : {default = [], file = 'travel_times.csv'}`

**Comment by KeeganShaw-GIS** [comment]
Was closed with V2.0
