### ISSUE TITLE
Describe the sensor  (GHG Sat?)

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [IM3S/LDAR_Sim#84]
https://github.com/IM3S/LDAR_Sim/blob/e6d6902a3c79d2eaa21f66d546a0d44b32433a99/LDAR_Sim/model_code/methods/sensors/satellite_sensor.py#L28

Also describe the MDL conversion (using wind speed)

**Comment by AkaMrmuffin** [comment]
Updated
