### ISSUE TITLE
Shapely not in requirements or pip loc file

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [IM3S/LDAR_Sim#86]
Added for Sat module

**Comment by KeeganShaw-GIS** [comment]
Try shapely-1.7.1 , that's what conda installs based on dependency tree.

**Comment by AkaMrmuffin** [comment]
Just added the shapely-1.7.1 into the loc wheels folder.

**Comment by KeeganShaw-GIS** [comment]
Also add orbit predictor!

**Comment by tbarchyn** [comment]
See PR #88

**Comment by tbarchyn** [comment]
Closing this one because I think it is in master now
