### ISSUE TITLE
Cost per site 

### ISSUE THREAD

**Issue by c-vollrath** [IM3S/LDAR_Sim#97]
@KeeganShaw-GIS and I discussed having a cost per site output in LDAR-Sim in addition to the total daily cost of the LDAR program that produces the rolling cost estimate. This could be an important output that producers are interested in - maybe they take a different approach to LDAR like a continuous monitor at their most expensive sites? This value could be output in a csv alongside facility ID and subtype code. 

Anyone want to weigh in on this? @tarcadius @tbarchyn @AkaMrmuffin @tybob-gough

**Comment by tarcadius** [comment]
I think this is a great idea. Implementation should be simple - new dictionary key "total_cost" for each site. After each visit (or initial up-front), $$ get added on. For technologies that are "cost per day", would need to estimate how long it took to survey that site and use that number with the daily rate and the "max hours per day" to calculate it. So, a bit of work, not crazy.

**Comment by KeeganShaw-GIS** [comment]
Fixed in V2
